### PR TITLE
update with new m3u8 urls, fixing audio issues

### PR DESCRIPTION
**Pull request by ilikenwf**
This fixes stream issues with audio and sync for me.

### CODE REVIEW

**Comment by ilikenwf** [comment]
So I'm an idiot, turns out this may be incorrect...I think we should revert.

**Comment by Powersurge** [comment]
No worries, I changed it back to the way it was.

**Comment by ilikenwf** [comment]
I wonder if someone should reach out to Infowars? Even their general live stream (not show specific, like the one we use here) - the official one on rumble, has the audio out of sync:

https://rumble.com/v17nm3j-infowars-network-feed-live-247.html

The show specific ones as they are right now work perfectly but it is nice to have the general link to watch so you don't have to change to a different stream 3 times a day.

**Comment by Powersurge** [comment]
Go for it! They are probably not even aware of this issue.

**Pull request merged**
